#!/bin/bash

if [ x"$@" = x"Appfinder" ];
then
killall rofi
sleep 0.25
featherpad /usr/share/rofi/appfinder-help
kill featherpad
fi

if [ x"$@" = x"Settings" ];
then
killall rofi
sleep 0.25
bash /usr/bin/appfinder-settings
fi

echo -e "Appfinder\0icon\x1fhelp-browser"
echo -e "Settings\0icon\x1fhelp-browser"
