#!/bin/bash

#DEBHELPER#

# postrm script for mxfb-accessories

#set -e

case "$1" in
  purge|remove) if [ -e "/etc/apt/apt.conf.d/00exectmp" ]; then
                  rm /etc/apt/apt.conf.d/00exectmp
                fi
                ;;

             *) :
                ;;
esac

exit 0
